### ISSUE TITLE
At ingest, at GET file, assign UID as SHA256

### ISSUE THREAD

**Issue by poorejc** [UMD-ARLIS/tika-document-ingest#9]
Execute SHA256 script off NiFi Get processor 

add SHA256 UUID key:value to flow file as authoritative UID

**Comment by Ky-Brown** [comment]
Generated SHA-256 field for each file ingested in NIFI. UUID field still exists in ES, however.
- notes: used built-in NIFI processor for SHA-256+ able to get rid of UUID if desired
